apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: auth-service
data:
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: "auth-service"
  OTEL_SERVICE_VERSION: "1.0.0"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
