apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 434473100946.dkr.ecr.us-east-1.amazonaws.com/auth-service:v1.0.1
          ports:
            - containerPort: 8001
              name: http
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets 
                  key: POSTGRES_PASSWORD
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: MASTER_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DATABASE_URL

          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"